### ISSUE TITLE
`fields` prop is not wired in ConfirmDialog

### ISSUE THREAD

**Issue by ruchamahabal** [frappe/frappe-ui#189]
https://github.com/frappe/frappe-ui/blob/a5147184122d7d8fd2d71af7caef2395708758f5/src/components/ConfirmDialog.vue#L1-L17

Remove it? Keep & wire it? Doesn't make sense to add fields in a confirm dialog anyway. This can be removed.

**Comment by nextchamp-saqib** [comment]
Remove it, this isn't used anywhere
