### ISSUE TITLE
Move frappeui.com -> ui.frappe.io

### ISSUE THREAD

**Issue by rmehta** [frappe/frappe-ui#190]

**Comment by cogk** [comment]
Also don't forget to add a 301 redirect from `frappeui.com` to `ui.frappe.io` to let search engines update their index and avoid dead links, at least for some time.

**Comment by surajshetty3416** [comment]
Done

[ui.frappe.io](https://ui.frappe.io) is hosted on GH pages. https://github.com/frappe/frappe-ui/pull/204
