### ISSUE TITLE
Typescript missing in production deployments

### ISSUE THREAD

**Issue by conncampbell** [frappe/frappe-ui#218]
When installed in production, non development environments, typescript is not included in the package.json; causing   errors during  build.

Error: [@vue/compiler-sfc] Failed to load TypeScript, which is required for resolving imported types. Please make sure "typescript" is installed as a project dependency.

/home/frappe/frappe-bench/apps/crm/node_modules/frappe-ui/src/components/Button.vue

The package file should have a typescript  dependency as below:

"dependencies": {
	"typescript": "^5.0.2"
},

**Comment by conncampbell** [comment]
I wonder if someone has put a bunch of dependencies in the dev portion of the package.json that should be in the production dependencies.

**Comment by ajmaltridz** [comment]
This needs to be fixed, affecting all of the down stream projects. Experienced with CRM and builder

**Comment by ruchamahabal** [comment]
Fixed https://github.com/frappe/frappe-ui/pull/221
