### ISSUE TITLE
Figma UI Kit

### ISSUE THREAD

**Issue by matbrgz** [frappe/frappe-ui#3]
Is there any kit on figma or any free software?

Best Regards

**Comment by matbrgz** [comment]
Is that possible? I want to help. I can start creating the basics components, and then we can arrange to adapt the look and feel of frappe.

**Comment by netchampfaris** [comment]
Frappe UI is extracted from products that we are building that have Figma mocks. Having a Figma UI Kit is ideal. But I am not a designer, and it's not a priority right now. If you are interested, you are free to create one. I would be happy to give feedback.

**Comment by netchampfaris** [comment]
We now have a UI Kit: https://www.figma.com/community/file/1407648399328528443/espresso-by-frappe
