### ISSUE TITLE
feat: use composables for resources

### ISSUE THREAD

**Issue by this-gavagai** [frappe/frappe-ui#31]
Right now, the $resources utility uses component mixins to expose Frappe resource apis. As of Vue 3, mixins are no longer the recommended approach for code reuse. 

> No Longer Recommended
> In Vue 2, mixins were the primary mechanism for creating reusable chunks of component logic. While mixins continue to be supported in Vue 3, [Composition API](https://vuejs.org/guide/reusability/composables.html) is now the preferred approach for code reuse between components.

https://vuejs.org/api/options-composition.html#mixins

I would propose that this library introduce a composables interface, exposing an importable method such as `useResources()` that would be available in Vue's composition API.

I believe it is possible for the library to offer both interfaces simultaneously, and I believe doing so would provide more flexibility in design patterning.

**Comment by NagariaHussain** [comment]
There are already three functions available for use in Composition API:

Check: src/resources/index.js

**Comment by this-gavagai** [comment]
Great, thanks so much. I don't know how I missed that. I'll give it a shot and report back.
