### ISSUE TITLE
Resources problem with array arg

### ISSUE THREAD

**Issue by britlog** [frappe/frappe-ui#4]
Hi,

When the arg is an array, only the first element is present in server side method.

Exemple of call in vue component :
```
resources: {
     todos: {
            method: 'custom_app.getStock',
            params: {
                fruits: ['Apple', 'Banana']
            },
            auto: true,
        }
  },
```

The payload is well sent : 
`{"fruits":["Apple","Banana"]}`

But in server side function getStock(fruits), print(fruits) gives :
`Apple`

If I change the arg to dict `{fruit1: 'Apple', fruit2: 'Banana'}`, it works and fruits arg is fully transmitted server side.

Thanks

**Comment by ankush** [comment]
related: https://github.com/frappe/frappe/pull/15784

**Comment by NagariaHussain** [comment]
You can try:

fruits: JSON.stringify(['Apple', 'Banana'])

if you don't have the latest Frappe fix.

**Comment by britlog** [comment]
stringify() works with `fruits = frappe.parse_json(fruits)` server side.

Thanks you both, I will try frappe 14 soon to check the fix
