### ISSUE TITLE
Is it possible to disable socket calls ?

### ISSUE THREAD

**Issue by vishwajeetaspl** [frappe/frappe-ui#44]
Hi , 
we have developed an UI from scratch from our but currently not using socket functionality and want to disable the calls from the client. Is there a flag by which we can disable it ?

**Comment by vishwajeetaspl** [comment]
@netchampfaris I asked about this in Frappeverse webinar and you said it's possible but I am unable to figure out how. If possible can you revert?

**Comment by netchampfaris** [comment]
```
app.use(FrappeUI, { socketio: false })
```

**Comment by vishwajeetaspl** [comment]
Than you @netchampfaris this helps . It doesn't seems to be working on the released version 0.0.31 but works well on tags 0.0.44. You can close this appreciate your support.
