### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Aslam97** [frappe/frappe-ui#50]
I followed the installation guide from https://frappeui.com/getting-started.html, but when I tried to access the URL todo.test:8080/frontend, I encountered an error message that said:

> Failed to resolve import '@tiptap/pm/state'
> Failed to resolve import 'prosemirror-model'

However, I was able to fix the issue by installing `@tiptap/pm` and then reloading the `/frontend` URL, which resolved the problem.

**Comment by iAlyousri** [comment]
in package.json
   "dependencies": {
    "@headlessui/vue": "^1.7.8",
    "@tiptap/pm": "^2.0.0-beta.210",
    "@tiptap/starter-kit": "2.0.0-beta.209",
    "@tiptap/vue-3": "2.0.0-beta.209",
    "canvas-datagrid": "^0.4.5",
    "docx-preview": "^0.1.14",
    "dropzone": "^6.0.0-beta.2",
    "feather-icons": "^4.29.0",
    "frappe-ui": "0.0.101",
    "fuzzysort": "^2.0.4",
    "mitt": "^3.0.0",
    "vue": "^3.2",
    "vue-router": "^4.1.6",
    "vuex": "^4.1.0",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.2.4",
    "vite": "^4.0"
  }

**Comment by iAlyousri** [comment]
> I followed the installation guide from https://frappeui.com/getting-started.html, but when I tried to access the URL todo.test:8080/frontend, I encountered an error message that said:
> 
> > Failed to resolve import '@tiptap/pm/state'
> > Failed to resolve import 'prosemirror-model'
> 
> However, I was able to fix the issue by installing `@tiptap/pm` and then reloading the `/frontend` URL, which resolved the problem.

--------
in package.json
"dependencies": {
"@headlessui/vue": "^1.7.8",
"@tiptap/pm": "^2.0.0-beta.210",
"@tiptap/starter-kit": "2.0.0-beta.209",
"@tiptap/vue-3": "2.0.0-beta.209",
"canvas-datagrid": "^0.4.5",
"docx-preview": "^0.1.14",
"dropzone": "^6.0.0-beta.2",
"feather-icons": "^4.29.0",
"frappe-ui": "0.0.101",
"fuzzysort": "^2.0.4",
"mitt": "^3.0.0",
"vue": "^3.2",
"vue-router": "^4.1.6",
"vuex": "^4.1.0",
"xlsx": "^0.18.5"
},
"devDependencies": {
"@vitejs/plugin-vue": "^4.0.0",
"autoprefixer": "^10.4.13",
"postcss": "^8.4.21",
"tailwindcss": "^3.2.4",
"vite": "^4.0"
}

**Comment by netchampfaris** [comment]
This is now fixed in latest version
