### ISSUE TITLE
Remove outline for clicked buttons

### ISSUE THREAD

**Issue by harshit-30** [frappe/frappe-ui#6]
the button remains selected after the action: 
![CleanShot 2022-05-04 at 17 17 38](https://user-images.githubusercontent.com/46772424/166675366-21578d39-e639-41ea-ac8a-25c2ac62c646.gif)

**Comment by netchampfaris** [comment]
Fixed via https://github.com/frappe/frappe-ui/commit/055e491e2e50292728eca7b4e4ae08fbe1374826
