### ISSUE TITLE
feature request: add label property to Autocomplete, DatePicker, TextEditor, etc

### ISSUE THREAD

**Issue by this-gavagai** [frappe/frappe-ui#71]
Components like Autocomplete and Date Picker are styled to blend with the default Input component. This creates a nice user experience, but at present only the input component has a `label` property. It would be more semantically robust if other similar components had this property too.

I am happy to submit a PR if this is consistent with the maintainers' vision.

**Comment by BreadGenie** [comment]
You can now use `FormControl` component with `type="autocomplete"` or `type="date"` for label as `FormControl` supports label.

reference: https://frappeui.com/story/src-components-formcontrol-story-vue?variantId=src-components-formcontrol-story-vue-3
