### ISSUE TITLE
Add dropdown item limit with overflow scroll

### ISSUE THREAD

**Issue by kamaljohnson** [frappe/frappe-ui#8]
Here instead of showing the entire dropdown items, it would be better if there is a limit, and the overflow would be scrollable 

![CleanShot 2022-05-13 at 14 34 21](https://user-images.githubusercontent.com/46772424/168250603-75d3b57f-c81d-4f20-99a0-33abbc0dc7a4.gif)

**Comment by harshit-30** [comment]
@netchampfaris can you check this out?

**Comment by netchampfaris** [comment]
Dropdown (Menu) should only be used for a limited set of options. The use-case shared in the GIF calls for a combobox component, where it shows a few options in a scrollable container with a search input which you can use to filter out the options.

More reading:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role

**Comment by netchampfaris** [comment]
I will probably add a generic combobox component in frappe-ui in the future

**Comment by kamaljohnson** [comment]
@netchampfaris i am actually using a Combobox component (from headless Ui) inside frappedesk, i could reflector it out into a frappe-ui component similar to the dropdown component.
